### ISSUE TITLE
Replace the parallel printing

### ISSUE THREAD

**Issue by Al2Klimov** [justinmueller05082000/check-scheduler#6]
... with one big loop with the same effect.

**Comment by justinmueller05082000** [comment]
can you give me an example for parallel printing

**Comment by Al2Klimov** [comment]
https://github.com/justinmueller05082000/check-scheduler/blob/fd8192ba3c40314c7cc22de553c03f2346f5f2c9/checkScheduler.go#L30

**Comment by Al2Klimov** [comment]
@justinmueller05082000 Please create a structure chart on paper before changing the code.

**Comment by justinmueller05082000** [comment]
![20191205_120923](https://user-images.githubusercontent.com/55092455/70230261-3ca18280-1758-11ea-9823-714bbd82e656.jpg)

**Comment by justinmueller05082000** [comment]
![20191205_120923](https://user-images.githubusercontent.com/55092455/70230515-cbae9a80-1758-11ea-90c6-a3a84dce25dd.jpg)
